### ISSUE TITLE
Make status update button easier to understand or provide help / usage information

### ISSUE THREAD

**Issue by julialeede** [ngandrass/moodle-quiz_archiver#21]
### Description

Hallo Nils, 

das ganze funktioniert auch ohne die Änderungsvorschläge sehr gut. Ich denke, dass eine gute Anleitung auch helfen kann. Da kann ich mich beteiligen.

Falls mal Kapazitäten da sind, wäre vielleicht folgendes interessant:
Nach dem Klick auf den Download ist es nicht ganz selbsterklärend, dass ich danach noch Mal auf den "Re-Load-Pfeil" klicken muss, um den Prozessstatus zu checken. Denn erst danach wird der Status als erstellt angezeigt. Folgendes könnte von der UX helfen:
- Vor dem Button könnte als Beschreibung "Check Status" stehen, was auch interaktiv sein sollte.
- Die Positionierg könnte eher auf Höhe der Symbole zum Start der Herstellung des Archivs sein, damit es noch mehr als zusammengehörigere Vorgang gesehen wird. Dadurch dass die Butttons am rechten Rand bunt sind, wandert der Blick eh eher dahin.
- Momentan ist die Status-Zeile an zweiter Stelle. Vielleicht könnte man sie auch eher rechts, hinter Size verschieben.
- Der Button könnte die Farbe wechseln, z.B. in Grün, wenn er fertig ist und in blau, wenn gerade ein Archiv erstellt wird..

**Comment by ngandrass** [comment]
In the future, I would love to have the job status page updated asynchronously, like with the asynchronous backups within Moodle itself. This would fully remove the need for full page refreshes to check the current job status. I'd also like to improve the job status reporting by providing progress information for longer running jobs.

Since this will cause some changes within the UI anyways, I'd postpone this discussion here until a draft of the new UI exists.

**Comment by ngandrass** [comment]
I finally found the time to come back to this issue. In the meantime the job status reporting improved a lot (see #26 and #28, both released with [version 1.4.0](https://github.com/ngandrass/moodle-quiz_archiver/releases/tag/v1.4.0)).

However, some aspects were still open. #36 addresses these now.

- The refresh button now has a proper tooltip.
![image](https://github.com/user-attachments/assets/fc25e77d-4bd9-4edd-a24f-bd9877f133ac)

- The time of the last refresh is displayed under the button so that a user more easily recognizes the connection between the button and the currency of the data displayed below.
![image](https://github.com/user-attachments/assets/8b258dcb-c5ba-4f52-8354-877a381cc987)

- The status column is now moved to the right. I did some tests and found the suggested column order to be both functional and visually appealing. This way, also colored parts are grouped together so the visual focus of the user does potentially not shift that strongly as before.
![Screenshot_20240812_175400](https://github.com/user-attachments/assets/596a7e41-e659-48e8-bf5a-250d65f5d570)

- All job status values now feature tooltips explaining the respective status.
![image](https://github.com/user-attachments/assets/92148da8-48f2-49ef-8a8b-3e21cd8122ba)
![image](https://github.com/user-attachments/assets/c91480cb-b984-4e07-8cd1-c9a70eaa31f5)

- I decided against moving the refresh button to another location. In my opinion an element should be positioned as close as possible to the part of a page that it affects. Since the table is potentially the only part of the page that changes during the refresh I'll keep the refresh button close to it.

- I decided against changing the color of the refresh button since the different status values are already displayed as distinctly colored status badges.
![image](https://github.com/user-attachments/assets/e63595f0-7fb7-4c98-8077-3a5e18def94b) ![image](https://github.com/user-attachments/assets/6ee29396-072a-4337-9b10-cd1425d1fd9e) ![image](https://github.com/user-attachments/assets/0ca3a9a7-e49f-4082-b82c-74eceeaf3974) ![image](https://github.com/user-attachments/assets/c2b7d88e-4708-4b1b-82f9-06c6641b4abb) ... and so on ...

**Comment by julialeede** [comment]
Lieber Nils,
danke, das sieht gut aus! Ich schaue es mir bei Gelegenheit an, wenn es bei uns im Testsystem installiert ist.
Ich frage Gisela, ob wir vielleicht in der Moodle-Dokumentation eine Seite dafür kriegen

Herzliche Grüße
Julia

Dear Nils,
Thank you, that looks good! I'll take a look at it when I get the chance, once it's installed in our test system.
I'll ask Gisela if we can get a page for this in the Moodle documentation

Best regards
Julia
