### ISSUE TITLE
Functionality to download/archive file attachments and submissions

### ISSUE THREAD

**Issue by martinoesterreicher** [ngandrass/moodle-quiz_archiver#5]
Currently we are using [quiz_downloadsubmissions](https://github.com/IITBombayWeb/moodle-quiz_downloadsubmissions/tree/master) as a means to download file attachments from quizzes. 
But that plugin is no longer maintained, the last change being 3 years ago. Currently it prevents moodle data requests to be performed. 

I think it would be a cool new feature for quiz_archiver if one could download and thus archive the file attachments as well.

**Comment by ngandrass** [comment]
Thanks for your suggestion :+1: 

Up until now I did not look into file submissions since the primary focus during development was the generation of PDF reports. Including submission files should be no problem, theoretically speaking.

Things to consider:

1. Currently, all submissions must be transferred to the archive worker service to be included in the archive. This could generate a lot of traffic, which is not critical as long as it is kept within an internal network.
2. The final archive can get ridiculously large.
3. We should change the file structure to create a separate subfolder for every attempt and store all related files in them. This would be required to keep the archive uncluttered when having multiple submission files.
4. If the archives get rather large, it could be desirable to provide an option to download individual attempts instead of the whole archive that contains all quiz attempts.

This is nothing I'll integrate in the next release since there are some other things, like the GDPR compliance (see #3), that I'd like to tackle before. However, I'll keep the issue open and will report back when I'll start working on this :)

**Comment by martinoesterreicher** [comment]
Perfect, thank you. :)
